apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    helm.sh/chart: nginx-0.1.0
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
